# Generated by Django 4.1.3 on 2022-11-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intexapp', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_journal',
            name='avg_blood_sugar',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='daily_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_albumin',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_blood_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_creatinine',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_potassium',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='lab_sodium',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='daily_journal',
            name='water_intake',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='phosphorus',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='water',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
