BEGIN;

--
-- Create model Comorbidity
--
CREATE TABLE "intexapp_comorbidity"(
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"comorbidity_name" varchar(25) NOT NULL	
 );
 
 
--
-- Create model Daily_Journal
--
CREATE TABLE "intexapp_daily_journal" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"date" date NOT NULL, 
"daily_weight" numeric(8, 2) ,
"avg_blood_sugar" numeric(8, 2),
"lab_blood_pressure" numeric(8, 2),
"lab_sodium" numeric(8, 2),
"lab_creatinine" numeric(8, 2),
"lab_albumin" numeric(8, 2) ,
"lab_potassium" numeric(8, 2),
"lab_phosphorus" numeric(8, 2),
"water_intake" numeric(8, 2)
 );

--
-- Create model Food
--
CREATE TABLE "intexapp_food" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"food_name" varchar(200) NOT NULL,
"sodium" numeric(8, 6) NOT NULL,
"protein" numeric(8, 6) NOT NULL,
"potassium" numeric(8, 6) NOT NULL,
"phosphorus" numeric(8, 6) NOT NULL,
"water" numeric(8, 6) NOT NULL
);


--
-- Create model User
--
CREATE TABLE "intexapp_user" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"first_name" varchar(25) NOT NULL,
"last_name" varchar(30) NOT NULL,
"dob" date NOT NULL,
"weight" numeric(8, 2) NOT NULL,
"height" numeric(8, 2) NOT NULL,
"gender" varchar(1) NOT NULL,
"stage" integer NOT NULL,
"username" varchar(20) NOT NULL,
"password" varchar(20) NOT NULL
);

CREATE TABLE "intexapp_user_comorbidities" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"user_id" bigint NOT NULL, 
"comorbidity_id" bigint NOT NULL
);

--
-- Create model Food_in_Day
--
CREATE TABLE "intexapp_food_in_day" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"grams" numeric(8, 2) NOT NULL,
"food_id" bigint NOT NULL,
"journal_id" bigint NOT NULL
 );
--
-- Add field daily_foods to daily_journal
--
-- (no-op)
--
-- Add field journal_user to daily_journal
--
ALTER TABLE "intexapp_daily_journal" 
ADD COLUMN "journal_user_id" 
bigint NOT NULL CONSTRAINT "intexapp_daily_journ_journal_user_id_fa0d8d5e_fk_intexapp_" 
REFERENCES "intexapp_user"("id") DEFERRABLE INITIALLY DEFERRED;

SET CONSTRAINTS "intexapp_daily_journ_journal_user_id_fa0d8d5e_fk_intexapp_" IMMEDIATE;

ALTER TABLE "intexapp_user_comorbidities" 
ADD CONSTRAINT "intexapp_user_comorbidit_user_id_comorbidity_id_a3cb22a2_uniq" 
UNIQUE ("user_id", "comorbidity_id");

ALTER TABLE "intexapp_user_comorbidities" 
ADD CONSTRAINT "intexapp_user_comorb_user_id_84cce5e8_fk_intexapp_" 
FOREIGN KEY ("user_id") 
REFERENCES "intexapp_user" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "intexapp_user_comorbidities" 
ADD CONSTRAINT "intexapp_user_comorb_comorbidity_id_c150e322_fk_intexapp_" 
FOREIGN KEY ("comorbidity_id") 
REFERENCES "intexapp_comorbidity" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "intexapp_user_comorbidities_user_id_84cce5e8" ON "intexapp_user_comorbidities" ("user_id");
CREATE INDEX "intexapp_user_comorbidities_comorbidity_id_c150e322" ON "intexapp_user_comorbidities" ("comorbidity_id");

ALTER TABLE "intexapp_food_in_day" 
ADD CONSTRAINT "intexapp_food_in_day_food_id_62574b35_fk_intexapp_food_id" 
FOREIGN KEY ("food_id") 
REFERENCES "intexapp_food" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "intexapp_food_in_day" 
ADD CONSTRAINT "intexapp_food_in_day_journal_id_ba254696_fk_intexapp_" 
FOREIGN KEY ("journal_id") 
REFERENCES "intexapp_daily_journal" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "intexapp_food_in_day_food_id_62574b35" 
ON "intexapp_food_in_day" ("food_id");

CREATE INDEX "intexapp_food_in_day_journal_id_ba254696" 
ON "intexapp_food_in_day" ("journal_id");

CREATE INDEX "intexapp_daily_journal_journal_user_id_fa0d8d5e" 
ON "intexapp_daily_journal" ("journal_user_id");
COMMIT;







